---
name: yambs-sample
description: A sample yambs project.

version:
  major: 0
  minor: 3
  patch: 0

config_local: |
  dependencies:
    - github: {repo: yambs-sample2, owner: *self}
    - github: {repo: yambs-sample3, owner: *self}
      as_source: true
